name: Deploy

on:
  push:
#    branches:
#      - releases
  workflow_dispatch:

jobs:

  deploy:

    runs-on: "ubuntu-latest"

    steps:
      - name: debug
        run:
          echo ${{ github.event.head_commit.message }}

#      - name: download library as artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: consigliere-${{ needs.build.outputs.version }}
#          path: dist/
#
#      - name: upload library to pypi
#        if: startsWith(github.ref, 'refs/tags')
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_TOKEN }}
#          verbose: true
